backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/post"
    create: true
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    path: '{{year}}/{{slug}}'
    fields:
      - { label: "Title", name: "Title", widget: "string" }
      - { label: "Date", name: "Date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
